// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) => User(
  (json['uid'] as num).toInt(),
  json['mobile'] as String,
  json['username'] as String,
  json['sex'] as String?,
  json['country'] as String?,
  json['province'] as String?,
  json['city'] as String?,
  json['signature'] as String,
  json['profilepicture'] as String?,
  (json['pwerrorcount'] as num?)?.toInt(),
  json['birthday'] as String?,
  (json['followers'] as num?)?.toInt(),
  (json['following'] as num?)?.toInt(),
  json['updatetime'] as String?,
  (json['likenum'] as num?)?.toInt(),
  json['token'] as String?,
  (json['likeact'] as num?)?.toInt(),
  (json['collectionact'] as num?)?.toInt(),
  (json['likecomment'] as num).toInt(),
  (json['likeevaluate'] as num?)?.toInt(),
  (json['collectionproduct'] as num?)?.toInt(),
  json['aliuserid'] as String,
  (json['likebug'] as num).toInt(),
  (json['likesuggest'] as num).toInt(),
  (json['likebugcomment'] as num).toInt(),
  (json['likesuggestcomment'] as num).toInt(),
  (json['likegoodpricecomment'] as num).toInt(),
  json['notinteresteduids'] as String?,
  json['blacklist'] as String?,
  json['goodpricenotinteresteduids'] as String?,
  (json['usertype'] as num?)?.toInt(),
  json['interest'] as String?,
  json['voice'] as String?,
  json['isNew'] as bool?,
  (json['business'] as num).toInt(),
  (json['likemoment'] as num).toInt(),
  (json['likemomentcomment'] as num).toInt(),
  json['wxuserid'] as String,
  json['iosuserid'] as String,
  json['subject'] as String,
)..isFollow = json['isFollow'] as bool;

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
  'uid': instance.uid,
  'username': instance.username,
  'sex': instance.sex,
  'country': instance.country,
  'province': instance.province,
  'city': instance.city,
  'signature': instance.signature,
  'profilepicture': instance.profilepicture,
  'pwerrorcount': instance.pwerrorcount,
  'birthday': instance.birthday,
  'followers': instance.followers,
  'following': instance.following,
  'isFollow': instance.isFollow,
  'updatetime': instance.updatetime,
  'likenum': instance.likenum,
  'token': instance.token,
  'likeact': instance.likeact,
  'collectionact': instance.collectionact,
  'likecomment': instance.likecomment,
  'likeevaluate': instance.likeevaluate,
  'collectionproduct': instance.collectionproduct,
  'aliuserid': instance.aliuserid,
  'wxuserid': instance.wxuserid,
  'iosuserid': instance.iosuserid,
  'likebug': instance.likebug,
  'likesuggest': instance.likesuggest,
  'likebugcomment': instance.likebugcomment,
  'likesuggestcomment': instance.likesuggestcomment,
  'likemoment': instance.likemoment,
  'likemomentcomment': instance.likemomentcomment,
  'likegoodpricecomment': instance.likegoodpricecomment,
  'mobile': instance.mobile,
  'notinteresteduids': instance.notinteresteduids,
  'blacklist': instance.blacklist,
  'goodpricenotinteresteduids': instance.goodpricenotinteresteduids,
  'usertype': instance.usertype,
  'interest': instance.interest,
  'voice': instance.voice,
  'isNew': instance.isNew,
  'business': instance.business,
  'subject': instance.subject,
};
