"""empty message

Revision ID: a79b49cab8cb
Revises: 
Create Date: 2025-10-18 18:36:49.518140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79b49cab8cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('actid', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('peoplenum', sa.Integer(), nullable=True),
    sa.Column('currentpeoplenum', sa.Integer(), nullable=True),
    sa.Column('startyear', sa.Integer(), nullable=True),
    sa.Column('endyear', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('addresstitle', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('actcity', sa.String(length=100), nullable=True),
    sa.Column('actprovince', sa.String(length=100), nullable=True),
    sa.Column('coverimg', sa.String(length=255), nullable=True),
    sa.Column('coverimgwh', sa.String(length=50), nullable=True),
    sa.Column('actimagespath', sa.Text(), nullable=True),
    sa.Column('maxcost', sa.Float(), nullable=True),
    sa.Column('mincost', sa.Float(), nullable=True),
    sa.Column('paytype', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=True),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('collectionnum', sa.Integer(), nullable=True),
    sa.Column('commentnum', sa.Integer(), nullable=True),
    sa.Column('viewnum', sa.Integer(), nullable=True),
    sa.Column('joinnum', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('actid')
    )
    op.create_table('activity_comment_likes',
    sa.Column('likeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('likeid'),
    sa.UniqueConstraint('commentid', 'uid', name='uq_comment_user_like')
    )
    with op.batch_alter_table('activity_comment_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_comment_likes_commentid'), ['commentid'], unique=False)

    op.create_table('activity_comment_replies',
    sa.Column('replyid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('actid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('replyid')
    )
    with op.batch_alter_table('activity_comment_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_comment_replies_commentid'), ['commentid'], unique=False)

    op.create_table('activity_comments',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('replynum', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('commentid')
    )
    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_comments_actid'), ['actid'], unique=False)

    op.create_table('good_price_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good_price_comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('likeuid', sa.Integer(), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good_price_comment_replies',
    sa.Column('replyid', sa.String(length=50), nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('replyid')
    )
    op.create_table('good_price_comments',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.create_table('good_price_evaluate_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluateid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('likeuid', sa.Integer(), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good_price_evaluate_replies',
    sa.Column('replyid', sa.String(length=50), nullable=False),
    sa.Column('evaluateid', sa.Integer(), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('replyid')
    )
    op.create_table('good_price_evaluates',
    sa.Column('evaluateid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('liketype', sa.Integer(), nullable=True),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('replynum', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('evaluateid')
    )
    op.create_table('good_price_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('liketype', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good_prices',
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('productnum', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('totalprice', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('originalprice', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('albumpics', sa.Text(), nullable=True),
    sa.Column('pic', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('citycode', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('addresstitle', sa.String(length=255), nullable=True),
    sa.Column('producturl', sa.String(length=500), nullable=True),
    sa.Column('purchasechannels', sa.String(length=100), nullable=True),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('unlikenum', sa.Integer(), nullable=True),
    sa.Column('collectionnum', sa.Integer(), nullable=True),
    sa.Column('commentnum', sa.Integer(), nullable=True),
    sa.Column('viewnum', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('statusmsg', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('goodpriceid')
    )
    op.create_table('group_purchase_orders',
    sa.Column('orderid', sa.String(length=50), nullable=False),
    sa.Column('actid', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=True),
    sa.Column('goodpriceid', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('paytime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('orderid')
    )
    op.create_table('moment_comment_likes',
    sa.Column('likeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('likeid'),
    sa.UniqueConstraint('commentid', 'uid', name='uq_moment_comment_user_like')
    )
    with op.batch_alter_table('moment_comment_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moment_comment_likes_commentid'), ['commentid'], unique=False)

    op.create_table('moment_comment_replies',
    sa.Column('replyid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('momentid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('replyid')
    )
    with op.batch_alter_table('moment_comment_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moment_comment_replies_commentid'), ['commentid'], unique=False)

    op.create_table('moment_comments',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('momentid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('touid', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('replynum', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('commentid')
    )
    with op.batch_alter_table('moment_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moment_comments_momentid'), ['momentid'], unique=False)

    op.create_table('moment_likes',
    sa.Column('likeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('momentid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('likeid'),
    sa.UniqueConstraint('momentid', 'uid', name='uq_moment_user_like')
    )
    with op.batch_alter_table('moment_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moment_likes_momentid'), ['momentid'], unique=False)

    op.create_table('moments',
    sa.Column('momentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('voice', sa.String(length=500), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('coverimgwh', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('commentnum', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('momentid')
    )
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moments_uid'), ['uid'], unique=False)

    op.create_table('sku_stocks',
    sa.Column('skuid', sa.String(length=50), nullable=False),
    sa.Column('goodpriceid', sa.String(length=50), nullable=False),
    sa.Column('skucode', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('lockstock', sa.Integer(), nullable=True),
    sa.Column('specs', sa.Text(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('skuid')
    )
    op.create_table('user_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('blacklistuid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'blacklistuid', name='uq_black_uid_user')
    )
    with op.batch_alter_table('user_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_blacklist_blacklistuid'), ['blacklistuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_blacklist_uid'), ['uid'], unique=False)

    op.create_table('user_follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('followed', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'followed', name='uq_follow_uid_followed')
    )
    with op.batch_alter_table('user_follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_follow_followed'), ['followed'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follow_uid'), ['uid'], unique=False)

    op.create_table('user_goodnotinteresteduids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('goodpricenotinteresteduid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'goodpricenotinteresteduid', name='uq_gp_notinterest_uid_user')
    )
    with op.batch_alter_table('user_goodnotinteresteduids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_goodnotinteresteduids_goodpricenotinteresteduid'), ['goodpricenotinteresteduid'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_goodnotinteresteduids_uid'), ['uid'], unique=False)

    op.create_table('user_notinteresteduids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('notinteresteduid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'notinteresteduid', name='uq_notinterest_uid_user')
    )
    with op.batch_alter_table('user_notinteresteduids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notinteresteduids_notinteresteduid'), ['notinteresteduid'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notinteresteduids_uid'), ['uid'], unique=False)

    op.create_table('user_push_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('pushtoken', sa.String(length=255), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_push_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_push_devices_uid'), ['uid'], unique=False)

    op.create_table('user_vcodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('vcode', sa.String(length=10), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_vcodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_vcodes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vcodes_mobile'), ['mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vcodes_uid'), ['uid'], unique=False)

    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('interest', sa.String(length=255), nullable=True),
    sa.Column('voice', sa.String(length=255), nullable=True),
    sa.Column('profilepicture', sa.String(length=255), nullable=True),
    sa.Column('usertype', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('weixin_openid', sa.String(length=64), nullable=True),
    sa.Column('ios_userid', sa.String(length=128), nullable=True),
    sa.Column('alipay_userid', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_mobile'), ['mobile'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mobile'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('user_vcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_vcodes_uid'))
        batch_op.drop_index(batch_op.f('ix_user_vcodes_mobile'))
        batch_op.drop_index(batch_op.f('ix_user_vcodes_email'))

    op.drop_table('user_vcodes')
    with op.batch_alter_table('user_push_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_push_devices_uid'))

    op.drop_table('user_push_devices')
    with op.batch_alter_table('user_notinteresteduids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notinteresteduids_uid'))
        batch_op.drop_index(batch_op.f('ix_user_notinteresteduids_notinteresteduid'))

    op.drop_table('user_notinteresteduids')
    with op.batch_alter_table('user_goodnotinteresteduids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_goodnotinteresteduids_uid'))
        batch_op.drop_index(batch_op.f('ix_user_goodnotinteresteduids_goodpricenotinteresteduid'))

    op.drop_table('user_goodnotinteresteduids')
    with op.batch_alter_table('user_follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follow_uid'))
        batch_op.drop_index(batch_op.f('ix_user_follow_followed'))

    op.drop_table('user_follow')
    with op.batch_alter_table('user_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blacklist_uid'))
        batch_op.drop_index(batch_op.f('ix_user_blacklist_blacklistuid'))

    op.drop_table('user_blacklist')
    op.drop_table('sku_stocks')
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moments_uid'))

    op.drop_table('moments')
    with op.batch_alter_table('moment_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moment_likes_momentid'))

    op.drop_table('moment_likes')
    with op.batch_alter_table('moment_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moment_comments_momentid'))

    op.drop_table('moment_comments')
    with op.batch_alter_table('moment_comment_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moment_comment_replies_commentid'))

    op.drop_table('moment_comment_replies')
    with op.batch_alter_table('moment_comment_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moment_comment_likes_commentid'))

    op.drop_table('moment_comment_likes')
    op.drop_table('group_purchase_orders')
    op.drop_table('good_prices')
    op.drop_table('good_price_likes')
    op.drop_table('good_price_evaluates')
    op.drop_table('good_price_evaluate_replies')
    op.drop_table('good_price_evaluate_likes')
    op.drop_table('good_price_comments')
    op.drop_table('good_price_comment_replies')
    op.drop_table('good_price_comment_likes')
    op.drop_table('good_price_collections')
    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_comments_actid'))

    op.drop_table('activity_comments')
    with op.batch_alter_table('activity_comment_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_comment_replies_commentid'))

    op.drop_table('activity_comment_replies')
    with op.batch_alter_table('activity_comment_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_comment_likes_commentid'))

    op.drop_table('activity_comment_likes')
    op.drop_table('activities')
    # ### end Alembic commands ###
