"""change users.sex to String(5)

Revision ID: f511a81cb7c9
Revises: a79b49cab8cb
Create Date: 2025-10-18 22:53:22.570410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f511a81cb7c9'
down_revision = 'a79b49cab8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
